package BSS;

/** \file Calculations.java
    \author Xinlu Yan
    \brief Provides functions for calculating the outputs
    \note Generated by Drasil v0.1-alpha
*/

import java.util.ArrayList;
import org.apache.commons.math3.ode.FirstOrderIntegrator;
import org.apache.commons.math3.ode.nonstiff.DormandPrince54Integrator;

public class Calculations {
    
    /** \brief Calculates dependent variables (m)
        \param m_2 mass of the second star (kg)
        \param m_1 mass of the first star (kg)
        \param x_1^0 initial x-position of the first star (m)
        \param y_1^0 initial y-position of the first star (m)
        \param x_2^0 initial x-position of the second star (m)
        \param y_2^0 initial y-position of the second star (m)
        \param v_x1^0 initial x-velocity of the first star (m/s)
        \param v_y1^0 initial y-velocity of the first star (m/s)
        \param v_x2^0 initial x-velocity of the second star (m/s)
        \param v_y2^0 initial y-velocity of the second star (m/s)
        \param t_final final time (s)
        \return dependent variables (m)
    */
    public static ArrayList<Double> func_q(double m_2, double m_1, double x_1^0, double y_1^0, double x_2^0, double y_2^0, double v_x1^0, double v_y1^0, double v_x2^0, double v_y2^0, double t_final) {
        ArrayList<Double> q;
        ODEStepHandler stepHandler = new ODEStepHandler();
        ODE ode = new ODE(m_1, m_2, x_1^0, y_1^0, x_2^0, y_2^0, v_x1^0, v_y1^0, v_x2^0, v_y2^0, t_final);
        double[] curr_vals = {x_1^0, y_1^0, x_2^0, y_2^0, v_x1^0, v_y1^0, v_x2^0, v_y2^0};
        
        FirstOrderIntegrator it = new DormandPrince54Integrator(10.0, 10.0, 1.0e-8, 1.0e-8);
        it.addStepHandler(stepHandler);
        it.integrate(ode, 0.0, curr_vals, t_final, curr_vals);
        q = stepHandler.q;
        
        return q;
    }
}
