package BSS;

/** \file OutputFormat.java
    \author Xinlu Yan
    \brief Provides the function for writing outputs
    \note Generated by Drasil v0.1-alpha
*/

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

public class OutputFormat {
    
    /** \brief Writes the output values to output.txt
        \param q dependent variables (m)
    */
    public static void write_output(ArrayList<ArrayList<Double>> q) throws IOException {
        PrintWriter outputfile;
        outputfile = new PrintWriter(new FileWriter(new File("output.txt"), false));
        outputfile.print("q = ");
        outputfile.println(q);
        outputfile.close();
    }
}
