/** \file OutputFormat.cs
    \author Xinlu Yan
    \brief Provides the function for writing outputs
    \note Generated by Drasil v0.1-alpha
*/

using System;
using System.Collections.Generic;
using System.IO;

public class OutputFormat {
    
    /** \brief Writes the output values to output.txt
        \param q dependent variables (m)
    */
    public static void write_output(List<List<double>> q) {
        StreamWriter outputfile;
        outputfile = new StreamWriter("output.txt", false);
        outputfile.Write("q = ");
        outputfile.Write("[");
        for (int list_i1 = 0; list_i1 < q.Count - 1; list_i1++) {
            outputfile.Write(q[list_i1]);
            outputfile.Write(", ");
        }
        if (q.Count > 0) {
            outputfile.Write(q[q.Count - 1]);
        }
        outputfile.WriteLine("]");
        outputfile.Close();
    }
}
