/** \file Control.cpp
    \author Xinlu Yan
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

#include <string>
#include <vector>

#include "Calculations.hpp"
#include "InputParameters.hpp"
#include "OutputFormat.hpp"

using std::string;
using std::vector;

/** \brief Controls the flow of the program
    \param argc Number of command-line arguments
    \param argv List of command-line arguments
    \return exit code
*/
int main(int argc, const char *argv[]) {
    string filename = argv[1];
    double m_1;
    double m_2;
    double x_1^0;
    double y_1^0;
    double x_2^0;
    double y_2^0;
    double v_x1^0;
    double v_y1^0;
    double v_x2^0;
    double v_y2^0;
    double t_final;
    get_input(filename, m_1, m_2, x_1^0, y_1^0, x_2^0, y_2^0, v_x1^0, v_y1^0, v_x2^0, v_y2^0, t_final);
    input_constraints(m_1, m_2, x_1^0, y_1^0, x_2^0, y_2^0, v_x1^0, v_y1^0, v_x2^0, v_y2^0, t_final);
    vector<double> q = func_q(m_2, m_1, x_1^0, y_1^0, x_2^0, y_2^0, v_x1^0, v_y1^0, v_x2^0, v_y2^0, t_final);
    write_output(q);
    
    return 0;
}
