/** \file ODE.hpp
    \author Xinlu Yan
    \brief Class representing an ODE system
    \note Generated by Drasil v0.1-alpha
*/

#ifndef ODE_h
#define ODE_h

#include <vector>

using std::vector;

/** \brief Class representing an ODE system
*/
class ODE {
    public:
        /** \brief Constructor for ODE objects
            \param m_1 mass of the first star (kg)
            \param m_2 mass of the second star (kg)
            \param x_1^0 initial x-position of the first star (m)
            \param y_1^0 initial y-position of the first star (m)
            \param x_2^0 initial x-position of the second star (m)
            \param y_2^0 initial y-position of the second star (m)
            \param v_x1^0 initial x-velocity of the first star (m/s)
            \param v_y1^0 initial y-velocity of the first star (m/s)
            \param v_x2^0 initial x-velocity of the second star (m/s)
            \param v_y2^0 initial y-velocity of the second star (m/s)
            \param t_final final time (s)
        */
        ODE(double m_1, double m_2, double x_1^0, double y_1^0, double x_2^0, double y_2^0, double v_x1^0, double v_y1^0, double v_x2^0, double v_y2^0, double t_final);
        /** \brief function representation of ODE system
            \param q dependent variables (m)
            \param dq change in dependent variables (m)
            \param t current independent variable value in ODE solution
        */
        void operator()(vector<double> q, vector<double> &dq, double t);
    
    private:
        double m_1;
        double m_2;
        double x_1^0;
        double y_1^0;
        double x_2^0;
        double y_2^0;
        double v_x1^0;
        double v_y1^0;
        double v_x2^0;
        double v_y2^0;
        double t_final;
        
};

#endif
