## \file Calculations.py
# \author Xinlu Yan
# \brief Provides functions for calculating the outputs
# \note Generated by Drasil v0.1-alpha

import math

import scipy.integrate

## \brief Calculates dependent variables (m)
# \param m_2 mass of the second star (kg)
# \param m_1 mass of the first star (kg)
# \param x_1^0 initial x-position of the first star (m)
# \param y_1^0 initial y-position of the first star (m)
# \param x_2^0 initial x-position of the second star (m)
# \param y_2^0 initial y-position of the second star (m)
# \param v_x1^0 initial x-velocity of the first star (m/s)
# \param v_y1^0 initial y-velocity of the first star (m/s)
# \param v_x2^0 initial x-velocity of the second star (m/s)
# \param v_y2^0 initial y-velocity of the second star (m/s)
# \param t_final final time (s)
# \return dependent variables (m)
def func_q(m_2, m_1, x_1^0, y_1^0, x_2^0, y_2^0, v_x1^0, v_y1^0, v_x2^0, v_y2^0, t_final):
    def f(t, q):
        return [q[4], q[5], q[6], q[7], -6.6743e-11 * m_2 * (q[0] - q[2]) / math.sqrt((q[0] - q[2]) ** 2.0 + (q[1] - q[3]) ** 2.0) ** 3.0, -6.6743e-11 * m_2 * (q[1] - q[3]) / math.sqrt((q[0] - q[2]) ** 2.0 + (q[1] - q[3]) ** 2.0) ** 3.0, 6.6743e-11 * m_1 * (q[0] - q[2]) / math.sqrt((q[0] - q[2]) ** 2.0 + (q[1] - q[3]) ** 2.0) ** 3.0, 6.6743e-11 * m_1 * (q[1] - q[3]) / math.sqrt((q[0] - q[2]) ** 2.0 + (q[1] - q[3]) ** 2.0) ** 3.0]
    
    r = scipy.integrate.ode(f)
    r.set_integrator("dopri5", atol=1.0e-8, rtol=1.0e-8)
    r.set_initial_value([x_1^0, y_1^0, x_2^0, y_2^0, v_x1^0, v_y1^0, v_x2^0, v_y2^0], 0.0)
    q = [[x_1^0, y_1^0, x_2^0, y_2^0, v_x1^0, v_y1^0, v_x2^0, v_y2^0][0]]
    while r.successful() and r.t < t_final:
        r.integrate(r.t + 10.0)
        q.append(r.y[0])
    
    return q
