## \file OutputFormat.py
# \author Xinlu Yan
# \brief Provides the function for writing outputs
# \note Generated by Drasil v0.1-alpha

## \brief Writes the output values to output.txt
# \param q dependent variables (m)
def write_output(q):
    outputfile = open("output.txt", "w")
    print("q = ", end="", file=outputfile)
    print(q, file=outputfile)
    outputfile.close()
